language: node_js

node_js:
  - '5.6.0'

branches:
  only:
  - master
  - /^deploy-.*$/

before_script:
  - npm install -g gulp
  - npm install -g typescript

script:
  - gulp clean
  - gulp build

install:
  - npm install
